image: maven:latest

variables:
  # Parent pom.xml
  PARENT_CLI_OPTS: "-f cognition/pom.xml -s .m2/settings.xml --batch-mode"
  # API pom.xml
  API_CLI_OPTS: "-f cognition/api/pom.xml -s .m2/settings.xml --batch-mode"
  # Core pom.xml
  CORE_CLI_OPTS: "-f cognition/core/pom.xml -s .m2/settings.xml --batch-mode"
  # UI pom.xml
  UI_CLI_OPTS: "-f cognition/ui/pom.xml -s .m2/settings.xml --batch-mode"

  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  # Cleans previous build, installs dependencies, runs all tests and checks that the project compiles
  script:
    - mvn $API_CLI_OPTS clean install
    - mvn $CORE_CLI_OPTS clean install
    - mvn $UI_CLI_OPTS clean # GitLab doesn't support TestFX, so we cannot run these tests
    - mvn $PARENT_CLI_OPTS compile -e

test:
  stage: test
  # This is strictly speaking unnecessary due to the script run above, but nice to have just in case.
  script:
    - mvn $API_CLI_OPTS clean test
    - mvn $CORE_CLI_OPTS clean test
