@startuml
class CogntionController{
- final CogntionService cogntionService
--
+ getCogntionStorage()
+ setCognitionStorage()
..
+ getUsers(): GET ("/users")
+ getUserByUsername(): GET ("/users/{username}")
+ createUser(): POST ("/users")
+ updateUser(): PUT ("/users")
+ deleteUser(): DELETE ("/users/{username}")
..
+ getQuizzesByUsername(): GET ("/quizzes/{username}")
+ getQuizTitlesByUsername(): GET ("/quizzes/{username}/titles")
+ getQuizByUuid(): GET ("/quiz/{uuid}")
+ updateQuizByUuid: PUT ("/quiz")
+ deleteQuizByUuid(): DELETE ("/quiz/{uuid}")
+ createQuiz(): POST ("/quiz/{username}")
}

class CognitionService{
- CognitionStorage cognitionStorage
+ getCognitionStorage()
+ setCogntionStorage()
}

class RestApplication{
- {static} int PORT
- {static} boolean testMode
+ {static} main()
+ setTestMode()
+ isTestMode()
}

RestApplication ..> CogntionController: <<Framework connection>>
CogntionController --> CognitionService
@enduml